name: Java CI

on: [push]

jobs:
  build:
    uses: ./.github/workflows/part-compile-and-test.yaml
    with:
      version: E-SNAPSHOT

  release:
    needs: build
    uses: ./.github/workflows/part-release.yaml
    secrets: inherit