name: Java CI

on: [push]

jobs:
  build:
    uses: ./.github/workflows/part-compile-and-test.yaml
    with:
      version: E-SNAPSHOT

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: download target directory
        uses: actions/download-artifact@v3
        with:
          name: target
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-push: "false"
          output-file: "false"
          skip-version-file: "true"
          skip-on-empty: "false"