name: Java CI

on: [push]

jobs:
  build:
    uses: ./.github/workflows/part-compile-and-test.yaml
  release:
    if: github.ref == 'refs/heads/master'
    needs: build
    uses: ./.github/workflows/part-release.yaml
    secrets: inherit
