name: compile and test our code
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5

      - name: Set tag name as version
        run: mvn -B versions:set -DnewVersion=${{ inputs.version }} --file pom.xml

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
#      - name: use-this-to-download-built-binaries
#        uses: actions/download-artifact@v3
#        with:
#          name: target
#          path: target